### ISSUE TITLE
build failure

### ISSUE THREAD

**Issue by pai01234** [ontio/ontology-java-sdk#124]
![image](https://user-images.githubusercontent.com/30950645/41763551-19d689d6-7631-11e8-908c-48531a1c456f.png)

**Comment by lucas7788** [comment]
@pai01234   具体是哪个测试类出错了，把出错的地方贴出来。

**Comment by pai01234** [comment]
应该是测试类assert里面少了一个方法

**Comment by pai01234** [comment]
https://github.com/ontio/ontology-java-sdk/issues/125#issuecomment-399624993
具体方法在这里
