### ISSUE TITLE
拉取源码后发现cant find the method

### ISSUE THREAD

**Issue by pai01234** [ontio/ontology-java-sdk#125]
![image](https://user-images.githubusercontent.com/30950645/41764257-24f05408-7633-11e8-9aba-ec3125580ce4.png)

**Comment by lucas7788** [comment]
应该是jar没有正确导入造成的，你把jar包重新导入一下试试，

**Comment by lucas7788** [comment]
@pai01234  应该是jar没有正确导入造成的，你把jar包重新导入一下试试。

**Comment by pai01234** [comment]
jar正常，这应该是assert类里面缺少这个方法，你们看下是否有提交

**Comment by lucas7788** [comment]
assert类不是我们写的，直接用的jar包里面的，所以不存在我们是否提交的问题

**Comment by lucas7788** [comment]
@pai01234    assert类不是我们写的，直接用的jar包里面的，所以不存在我们是否提交的问题

**Comment by lucas7788** [comment]
@pai01234   jar包是通过mvn管理的

**Comment by pai01234** [comment]
我把测试的package删除了重新打包后就可以了

**Comment by pai01234** [comment]
测试的package里面有会用到的api吗，还是说没有用到呢

**Comment by lucas7788** [comment]
@pai01234  测试包里面没有用到的api
