### ISSUE TITLE
server response error

### ISSUE THREAD

**Issue by prettyCoders** [ontio/ontology-java-sdk#144]
I use java-sdk connet mainnet,It returns me an exception
![qq 20180702161916](https://user-images.githubusercontent.com/36216120/42152833-ee1c039e-7e13-11e8-8d71-cf0fcc12c1e1.png)
this is my code:
  OntSdk ontSdk=OntSdk.getInstance();
  ontSdk.setRestful("http://127.0.0.1:20338");
  int height = ontSdk.getConnect().getBlockHeight();
  System.out.println("height:"+height);

this is my node:
2018/07/02 16:24:57.903839 [INFO ] GID 319, CurrentBlockHeight = 4470
2018/07/02 16:25:03.903877 [INFO ] GID 319, CurrentBlockHeight = 4470
2018/07/02 16:25:04.897930 [INFO ] GID 169747, syncHeader request Height:4471
2018/07/02 16:25:04.930807 [INFO ] GID 169750, OnHeaderReceive Height:4471 - 4472
2018/07/02 16:25:09.903835 [INFO ] GID 319, CurrentBlockHeight = 4472
2018/07/02 16:25:14.319098 [INFO ] GID 169942, connect ip address: 13.125.46.194:20338
2018/07/02 16:25:14.319159 [INFO ] GID 169942, connect ip address: 86.150.144.101:20338
2018/07/02 16:25:14.319185 [INFO ] GID 169942, connect ip address: 47.52.114.209:20338
2018/07/02 16:25:14.319205 [INFO ] GID 169942, connect ip address: 58.173.217.208:20338
2018/07/02 16:25:14.319223 [INFO ] GID 169942, connect ip address: 107.184.212.90:20338
2018/07/02 16:25:14.319241 [INFO ] GID 169942, connect ip address: 139.129.235.173:20338
2018/07/02 16:25:14.319259 [INFO ] GID 169942, connect ip address: 104.211.206.193:20338
2018/07/02 16:25:14.319275 [INFO ] GID 169942, connect ip address: 47.91.248.37:30164
2018/07/02 16:25:15.903824 [INFO ] GID 319, CurrentBlockHeight = 4472

**Comment by xizho10** [comment]
Restful port is 20334， not 20338

**Comment by prettyCoders** [comment]
@xizho10 I midify the pot to 20334,Same result!

**Comment by prettyCoders** [comment]
Note:mainnet,not testnet!

**Comment by prettyCoders** [comment]
![port](https://user-images.githubusercontent.com/36216120/42154022-5263f0fc-7e17-11e8-9832-62b79cf56b71.png)

**Comment by xizho10** [comment]
You need to enable restful: ./ontology --networkid 1 --rest
Only open rpc  default

**Comment by prettyCoders** [comment]
谢了，上海的哥们儿！
