### ISSUE TITLE
i use the WasmDemo.java get an error

### ISSUE THREAD

**Issue by xiangjianmeng** [ontio/ontology-java-sdk#166]
Code:0061736d0100000001070160027f7f017f030201000404017000000503010001071002066d656d6f727902000373756d00000a09010700200120006a0b
CodeAddress:97a5272fddaf6ea6060537649d190e72c42088f4
00d08adf1fdd020000000000000080c3c9010000000035e8236fadbe437a3fd2dae3f5db44550c144c533d0061736d0100000001070160027f7f017f030201000404017000000503010001071002066d656d6f727902000373756d00000a09010700200120006a0b01046e616d6503312e300131013101310000
POST url=http://127.0.0.1:20334/api/v1/transaction,{},{"Action":"sendrawtransaction","Version":"v1.0.0","Data":"00d08adf1fdd020000000000000080c3c9010000000035e8236fadbe437a3fd2dae3f5db44550c144c533d0061736d0100000001070160027f7f017f030201000404017000000503010001071002066d656d6f727902000373756d00000a09010700200120006a0b01046e616d6503312e300131013101310000"}
com.github.ontio.network.exception.RestfulException: {"Action":"sendrawtransaction","Desc":"","Error":-1,"Result":"transactor 534c140c5544dbf5e3dad23f7a43bead6f23e835 has no balance enough to cover gas cost 40000000","Version":"1.0.0"}
	at com.github.ontio.network.rest.RestClient.sendRawTransaction(RestClient.java:55)
	at com.github.ontio.network.rest.RestClient.sendRawTransaction(RestClient.java:35)
	at com.github.ontio.sdk.manager.ConnectMgr.sendRawTransaction(ConnectMgr.java:117)
	at com.okchain.App.main(App.java:48)

**Comment by xizho10** [comment]
Insufficient balance you your account

**Comment by xiangjianmeng** [comment]
Can now ONT support wasm smart contract？

**Comment by xizho10** [comment]
yes  not support wasm smart contract now
