### ISSUE TITLE
Adding back support for other cryptographic algorithms 

### ISSUE THREAD

**Issue by backslash47** [ontio/ontology-java-sdk#49]
Hello, 

In commit https://github.com/ontio/ontology-java-sdk/commit/d7721eb3259e35db1d14fcbd7e91a9a027916d25 there was removed (maybe unintentionally) support for other key types than ECDSA, therefore it is not possible to construct SM2 key and use it for signing. 

If it was unintentional I might propose a pull request where the support is added and also the bug in SM3withSM2 signature verification is fixed. You can see the necessary changes in https://github.com/backslash47/ontology-java-sdk/commit/2cfa573ead5b1b28560d6f2dd597831552e20c03

**Comment by xizho10** [comment]
it is unintentionally. welcome to contribute SM3WITHSM2。
